---
development:
  cloud_name: doaankgcu
  api_key: '173847825615475'
  api_secret: Gt-lxfaxKJKuJOfpsuvUSub0bEA
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: doaankgcu
  api_key: '173847825615475'
  api_secret: Gt-lxfaxKJKuJOfpsuvUSub0bEA
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: doaankgcu
  api_key: '173847825615475'
  api_secret: Gt-lxfaxKJKuJOfpsuvUSub0bEA
  enhance_image_tag: true
  static_image_support: false
